[package]
name = "goat-providers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
goat-provider = { workspace = true }
goat-auth = { workspace = true }
goat-config = { workspace = true }
goat-proxy = { workspace = true }
tokio = { workspace = true }
goat-provider-builtin = { workspace = true }
goat-provider-openai-codex = { workspace = true }
goat-provider-anthropic = { workspace = true }
goat-provider-gemini = { workspace = true }
goat-provider-kimi-code = { workspace = true }
goat-provider-xai = { workspace = true }

[lints]
workspace = true
