[package]
name = "goat-provider-local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
goat-provider-openai-compat = { workspace = true }

[dev-dependencies]
goat-provider = { workspace = true }

[lints]
workspace = true
