[package]
name = "goat-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
goat-tool = { workspace = true }
goat-tool-ask = { workspace = true }
goat-tool-delegate = { workspace = true }
goat-tool-plan = { workspace = true }
goat-tool-fs = { workspace = true }
goat-tool-shell = { workspace = true }
goat-tool-search = { workspace = true }
goat-tool-skill = { workspace = true }
goat-tool-web = { workspace = true }
goat-protocol = { workspace = true }
tokio-util = { workspace = true }

[lints]
workspace = true
