[package]
name = "goat-command-settings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
goat-command = { workspace = true }
goat-api = { workspace = true }
serde_json = { workspace = true }
goat-config = { workspace = true }
goat-auth = { workspace = true }
goat-search-provider = { workspace = true }
goat-search-providers = { workspace = true }
goat-protocol = { workspace = true }
goat-client = { workspace = true }
goat-github = { workspace = true }
goat-worktree = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
unicode-width = { workspace = true }

[lints]
workspace = true
