ALTER TABLE personas RENAME TO agents;
ALTER TABLE threads RENAME COLUMN persona_id TO agent_id;
ALTER TABLE messages RENAME COLUMN persona_id TO agent_id;
ALTER TABLE core_memory RENAME COLUMN persona_id TO agent_id;
ALTER TABLE tool_invocations RENAME COLUMN persona_id TO agent_id;
ALTER TABLE scheduled_tasks RENAME COLUMN persona_id TO agent_id;
ALTER TABLE thread_summary RENAME COLUMN persona_id TO agent_id;
ALTER TABLE goals RENAME COLUMN persona_id TO agent_id;
ALTER TABLE integration_state RENAME COLUMN persona_id TO agent_id;
ALTER TABLE integration_observations RENAME COLUMN persona_id TO agent_id;
DROP INDEX idx_conv_persona;
CREATE INDEX idx_threads_agent ON threads(agent_id);
DROP INDEX idx_messages_persona_ts;
CREATE INDEX idx_messages_agent_ts ON messages(agent_id, ts);
DROP INDEX idx_tool_invocations_persona;
CREATE INDEX idx_tool_invocations_agent ON tool_invocations(agent_id, started_at);
DROP INDEX idx_scheduled_tasks_persona_status;
CREATE INDEX idx_scheduled_tasks_agent_status ON scheduled_tasks(agent_id, status);
DROP INDEX idx_goals_persona_status;
CREATE INDEX idx_goals_agent_status ON goals(agent_id, status);
