pub enum CommandEffect {
    OpenModelPicker,
    SelectModelNamed(String),
    OpenEffortPicker,
    SelectEffort(String),
    OpenThreadPicker,
    ResumeIndex(usize),
    OpenRewind,
    OpenConfig,
    ShowHelp,
    ClearConversation,
    CompactConversation(Option<String>),
    TogglePlanMode,
    RenameConversation(String),
    Submit(String),
    SubmitCommand { display: String, prompt: String },
    Notice(String),
    Error(String),
    OpenUsage,
    OpenStatus,
    Noop,
    Quit,
}
