ALTER TABLE code_threads RENAME TO code_conversations;
ALTER TABLE code_turns RENAME COLUMN thread_id TO conversation_id;
ALTER TABLE code_messages RENAME COLUMN thread_id TO conversation_id;
ALTER TABLE code_tool_calls RENAME COLUMN thread_id TO conversation_id;
ALTER TABLE code_compactions RENAME COLUMN thread_id TO conversation_id;
ALTER TABLE code_open_prompts RENAME COLUMN thread_id TO conversation_id;
ALTER TABLE code_checkpoints RENAME COLUMN thread_id TO conversation_id;
DROP INDEX idx_code_threads_cwd;
CREATE INDEX idx_code_conversations_cwd ON code_conversations(cwd);
DROP INDEX idx_code_turns_thread;
CREATE INDEX idx_code_turns_conversation ON code_turns(conversation_id);
DROP INDEX idx_code_messages_thread;
CREATE INDEX idx_code_messages_conversation ON code_messages(conversation_id);
DROP INDEX idx_code_tool_calls_thread;
CREATE INDEX idx_code_tool_calls_conversation ON code_tool_calls(conversation_id);
DROP INDEX idx_code_compactions_thread;
CREATE INDEX idx_code_compactions_conversation ON code_compactions(conversation_id);
DROP INDEX idx_code_checkpoints_thread;
CREATE INDEX idx_code_checkpoints_conversation ON code_checkpoints(conversation_id);
